services:
  frontend:
    build:
      context: ./tarkov-planner-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - network

  backend:
    build:
      context: ./tarkov-planner-backend
    ports:
      - "8000:8000"
    environment:
      - RATE_LIMIT=20
    networks:
      - network

networks:
  network:
    name: tarkov-planner_network
    driver: bridge
